# Generated by Django 4.0 on 2025-02-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Y', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Y.tweet'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tweet')},
        ),
    ]
