# Generated by Django 5.1.6 on 2025-02-28 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Y', '0006_tweet_original_tweet_tweet_parent_tweet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together={('user', 'original_tweet')},
        ),
    ]
