# Generated by Django 5.1.6 on 2025-02-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Y', '0007_notification_message_alter_tweet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'いいね'), ('follow', 'フォロー'), ('tweet', '新規ツイート')], max_length=10),
        ),
    ]
