# Generated by Django 5.1.6 on 2025-02-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Y', '0009_remove_notification_message_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Y.directmessage'),
        ),
    ]
